// ─── COURSE CATALOGUE ─────────────────────────────────────────────────────────
// The canonical list of Skills for Care mandatory courses. Each course has a
// summary, learning objectives, content slides (each with a visual type), and a
// multiple-choice assessment. Served to the frontend via /api/courses.
//
// Slide visual types (rendered by the course player):
//   stat     visualData: { stats: [{n, l}] }            big figures
//   grid     visualData: { items: ["..."] }             numbered tags
//   flow     visualData: { steps: ["..."] }             a step-by-step process
//   pillars  visualData: { items: ["..."] }             labelled columns
//   compare  visualData: { left:{title,items}, right:{title,items} }   do / don't
//   cycle    visualData: { items: ["..."] }             a loop / chain
//   icon     (no data)                                  the course icon

export const COURSES = [
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "safeguarding", title: "Safeguarding Adults", icon: "🛡️", color: "#1B4F72", duration: "45 min",
    summary: "Recognise, respond to and report abuse and neglect of adults at risk.",
    objectives: [
      "Define safeguarding and explain who counts as an adult at risk",
      "Recognise the ten categories of abuse and their warning signs",
      "Apply the six safeguarding principles to your practice",
      "Respond and report correctly when you suspect abuse",
    ],
    slides: [
      { heading: "What is Safeguarding?", visual: "stat",
        visualData: { stats: [{ n: "2M+", l: "Adults receiving care in England" }, { n: "500K+", l: "Safeguarding concerns raised /yr" }, { n: "6", l: "Core principles" }] },
        body: "Safeguarding means protecting an adult's right to live in safety, free from abuse and neglect. Under the Care Act 2014, local authorities have a legal duty to protect adults at risk.",
        points: ["An 'adult at risk' has care and support needs", "They may be unable to protect themselves from harm", "Safeguarding is everyone's responsibility", "The adult's own wishes stay central to any action"] },
      { heading: "The 10 Types of Abuse", visual: "grid",
        visualData: { items: ["Physical", "Sexual", "Psychological", "Financial", "Neglect", "Discriminatory", "Organisational", "Domestic", "Modern Slavery", "Self-neglect"] },
        body: "The Care Act 2014 sets out ten categories of abuse and neglect. You must be able to recognise each one.",
        points: ["Abuse can be a single act or repeated over time", "It can be deliberate or the result of ignorance", "It can happen anywhere, by anyone", "Often more than one type occurs together"] },
      { heading: "Recognising the Signs", visual: "compare",
        visualData: { left: { title: "Possible signs", items: ["Unexplained injuries or bruising", "Sudden changes in behaviour", "Withdrawal or fearfulness", "Unexplained money problems", "Poor hygiene or weight loss"] }, right: { title: "Your response", items: ["Stay calm and reassure", "Listen — do not interrogate", "Preserve any evidence", "Record exactly what you saw/heard", "Report without delay"] } },
        body: "Signs are not proof, but they are reasons to be alert and to report your concern. Never assume someone else will raise it.",
        points: ["Trust your professional instinct", "A disclosure may be the only sign you get", "Believe the person and take them seriously"] },
      { heading: "The 6 Safeguarding Principles", visual: "pillars",
        visualData: { items: ["Empowerment", "Prevention", "Proportionality", "Protection", "Partnership", "Accountability"] },
        body: "The Care Act 2014 sets six principles that underpin all safeguarding activity.",
        points: ["Empowerment — support people's own decisions", "Prevention — act before harm occurs", "Proportionality — the least intrusive response", "Protection — support for those in greatest need", "Partnership — local services working together", "Accountability — transparency in safeguarding"] },
      { heading: "How to Report a Concern", visual: "flow",
        visualData: { steps: ["Ensure immediate safety", "Do NOT investigate yourself", "Tell your safeguarding lead / manager", "Record facts clearly and promptly", "Follow your organisation's procedure"] },
        body: "If you suspect abuse, acting quickly and correctly protects the person. Reporting is a duty, not a choice.",
        points: ["In an emergency call 999 first", "Never confront the alleged abuser", "Never promise to keep a disclosure secret", "If your manager is implicated, escalate above them or to the local authority"] },
    ],
    quiz: [
      { q: "Under which legislation do local authorities have a statutory duty to safeguard adults at risk?", options: ["Mental Health Act 2007", "Care Act 2014", "Health and Social Care Act 2012", "Mental Capacity Act 2005"], answer: 1, explanation: "The Care Act 2014 placed adult safeguarding on a statutory footing." },
      { q: "How many categories of abuse does the Care Act 2014 identify?", options: ["6", "8", "10", "12"], answer: 2, explanation: "The Care Act 2014 identifies 10 types of abuse and neglect." },
      { q: "Which principle means using the least intrusive response appropriate to the risk?", options: ["Prevention", "Protection", "Proportionality", "Partnership"], answer: 2, explanation: "Proportionality means the response should be the least intrusive necessary." },
      { q: "A service user discloses abuse and asks you to keep it secret. What should you do?", options: ["Agree, to keep their trust", "Explain you must pass it on to keep them safe, then report", "Only report if you see proof", "Decide later"], answer: 1, explanation: "You cannot keep abuse secret. Be honest that you must report it to keep them safe." },
      { q: "You suspect a colleague is financially abusing a service user. What is your first action?", options: ["Confront the colleague", "Investigate it yourself", "Report to your manager or safeguarding lead immediately", "Wait to be certain"], answer: 2, explanation: "Report immediately. Never investigate or confront the alleged abuser yourself." },
      { q: "Which of these is a recognised type of abuse under the Care Act?", options: ["Self-neglect", "Forgetfulness", "Shyness", "Tiredness"], answer: 0, explanation: "Self-neglect is one of the ten recognised categories." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "fire-safety", title: "Fire Safety", icon: "🔥", color: "#922B21", duration: "30 min",
    summary: "Prevent fires and respond safely to protect the people in your care.",
    objectives: [
      "Explain the fire triangle and how to prevent fires",
      "Follow the RACE procedure in a fire emergency",
      "Identify the correct fire extinguisher for each fire type",
      "Support a safe evacuation of people in your care",
    ],
    slides: [
      { heading: "The Fire Triangle", visual: "pillars",
        visualData: { items: ["Fuel", "Heat", "Oxygen"] },
        body: "Fire needs three elements together. Remove any one and the fire cannot start or continue.",
        points: ["Fuel — anything that can burn", "Heat — a source of ignition", "Oxygen — present in the air around us", "Good prevention removes one side of the triangle"] },
      { heading: "Preventing Fires in Care", visual: "compare",
        visualData: { left: { title: "Common risks", items: ["Overloaded sockets", "Faulty electrical equipment", "Smoking materials", "Cooking left unattended", "Blocked fire exits"] }, right: { title: "Good practice", items: ["Report damaged wiring", "Keep exits clear at all times", "Follow the smoking policy", "Never wedge fire doors open", "Know your evacuation plan"] } },
        body: "Most fires are preventable. Day-to-day vigilance is the most effective protection.",
        points: ["Fire doors save lives — keep them shut", "PEEPs set out how each person will be evacuated"] },
      { heading: "RACE — Your Response", visual: "flow",
        visualData: { steps: ["Rescue anyone in immediate danger", "Alert — raise the alarm, call 999", "Contain — close doors and windows", "Evacuate or Extinguish if safe"] },
        body: "In a fire, follow RACE without hesitation. Your priority is always people, not property.",
        points: ["Only tackle a fire if it is small and you are trained", "Never put yourself at risk", "Use the nearest safe exit"] },
      { heading: "Extinguisher Types", visual: "grid",
        visualData: { items: ["Water — wood/paper", "Foam — flammable liquids", "CO₂ — electrical", "Dry powder — multi", "Wet chemical — cooking oil"] },
        body: "Using the wrong extinguisher can make a fire far worse. Match the extinguisher to the fire.",
        points: ["Never use water on electrical or oil fires", "CO₂ (black label) is for electrical fires", "Wet chemical (yellow) is for deep-fat fryers", "If in doubt, evacuate instead"] },
      { heading: "Using an Extinguisher — PASS", visual: "flow",
        visualData: { steps: ["Pull the safety pin", "Aim at the base of the fire", "Squeeze the handle", "Sweep side to side"] },
        body: "If it is safe and you are trained, the PASS technique is used for all extinguisher types.",
        points: ["Always keep an exit behind you", "Stand back a safe distance", "If the fire grows, get out immediately"] },
    ],
    quiz: [
      { q: "Which element of the fire triangle must you remove to stop a fire?", options: ["All three at once", "Any one of fuel, heat, or oxygen", "Only oxygen", "Only heat"], answer: 1, explanation: "Removing any single element of the triangle stops the fire." },
      { q: "What does the 'C' in RACE stand for?", options: ["Call the brigade", "Contain by closing doors", "Check the building", "Carry residents out"], answer: 1, explanation: "Contain — closing doors and windows slows the spread of fire and smoke." },
      { q: "Which extinguisher is correct for an electrical fire?", options: ["Water", "Foam", "CO₂", "Wet chemical"], answer: 2, explanation: "CO₂ (black label) is correct for electrical fires. Never use water." },
      { q: "What does the 'A' in the PASS technique stand for?", options: ["Alert", "Aim at the base of the fire", "Activate", "Approach"], answer: 1, explanation: "Aim at the base of the fire, not the flames." },
      { q: "Why must fire doors never be wedged open?", options: ["They look untidy", "They contain fire and smoke when closed", "It damages the hinges", "It is against the smoking policy"], answer: 1, explanation: "Closed fire doors slow the spread of fire and smoke, protecting escape routes." },
      { q: "What is your top priority in a fire?", options: ["Saving equipment", "Protecting the building", "The safety of people", "Finding the cause"], answer: 2, explanation: "People always come before property." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "infection-control", title: "Infection Prevention & Control", icon: "🦠", color: "#1E8449", duration: "40 min",
    summary: "Break the chain of infection and protect people through safe practice.",
    objectives: [
      "Describe the chain of infection and how to break it",
      "Perform hand hygiene at the right moments and to the right standard",
      "Put on and remove PPE in the correct order",
      "Apply standard precautions in everyday care",
    ],
    slides: [
      { heading: "The Chain of Infection", visual: "cycle",
        visualData: { items: ["Infectious agent", "Reservoir", "Portal of exit", "Transmission", "Portal of entry", "Susceptible host"] },
        body: "Infection spreads through six linked stages. Breaking any single link stops the infection spreading.",
        points: ["Most links are broken by good hygiene", "Hand hygiene breaks the transmission link", "PPE protects portals of entry and exit", "Cleaning removes reservoirs"] },
      { heading: "Standard Precautions", visual: "grid",
        visualData: { items: ["Hand hygiene", "PPE", "Safe sharps", "Waste disposal", "Spillage management", "Clean equipment"] },
        body: "Standard precautions are applied to everyone, all the time, regardless of known infection status.",
        points: ["Assume all blood and body fluids are infectious", "Protect yourself and the people you care for", "Consistency is what keeps everyone safe"] },
      { heading: "The 5 Moments for Hand Hygiene", visual: "flow",
        visualData: { steps: ["Before touching a person", "Before a clean/aseptic task", "After body-fluid exposure risk", "After touching a person", "After touching their surroundings"] },
        body: "The WHO 'Five Moments' identify exactly when hand hygiene is critical.",
        points: ["Wash for at least 20 seconds", "Cover all surfaces, including thumbs and fingertips", "Use soap and water if hands are visibly soiled", "Alcohol gel is fine when hands look clean"] },
      { heading: "PPE — The Right Order", visual: "compare",
        visualData: { left: { title: "Putting ON", items: ["1. Apron", "2. Mask", "3. Eye protection", "4. Gloves"] }, right: { title: "Taking OFF", items: ["1. Gloves", "2. Eye protection", "3. Apron", "4. Mask"] } },
        body: "Order matters. Remove the most contaminated items first to avoid spreading infection.",
        points: ["Change gloves between tasks and people", "Never reuse single-use PPE", "Hand hygiene after removing all PPE"] },
      { heading: "Safe Waste & Sharps", visual: "grid",
        visualData: { items: ["Yellow — infectious", "Orange — clinical", "Black — domestic", "Sharps bin — needles", "Never overfill", "Never recap needles"] },
        body: "Correct segregation and sharps handling prevents injury and cross-infection.",
        points: ["Dispose of sharps at the point of use", "Sharps bins are filled only to the marked line", "Report any sharps injury immediately"] },
    ],
    quiz: [
      { q: "Breaking which link in the chain of infection stops transmission?", options: ["Only the agent", "Any single link", "Only transmission", "Entry and exit together"], answer: 1, explanation: "Breaking any single link interrupts the chain." },
      { q: "How long should effective handwashing take?", options: ["5 seconds", "10 seconds", "At least 20 seconds", "60 seconds"], answer: 2, explanation: "At least 20 seconds, covering all surfaces of the hands." },
      { q: "What is the correct order for removing PPE?", options: ["Mask first", "Apron first", "Gloves → eye protection → apron → mask", "Any order is fine"], answer: 2, explanation: "Remove the most contaminated items first: gloves, then eye protection, apron, and mask." },
      { q: "To whom do standard precautions apply?", options: ["Only people with a known infection", "Only during outbreaks", "Everyone, all the time", "Only in hospitals"], answer: 2, explanation: "Standard precautions apply to everyone, at all times." },
      { q: "When should you dispose of a sharp?", options: ["At the end of your shift", "At the point of use, immediately", "Once the bin is full", "After recapping the needle"], answer: 1, explanation: "Dispose of sharps immediately at the point of use; never recap needles." },
      { q: "Which colour bin is used for infectious waste?", options: ["Black", "Yellow", "Blue", "Green"], answer: 1, explanation: "Yellow is used for infectious waste in the UK colour-coded system." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "health-safety", title: "Health & Safety", icon: "⛑️", color: "#6B4226", duration: "35 min",
    summary: "Understand your health and safety duties and keep your workplace safe.",
    objectives: [
      "Identify the key health and safety legislation in care",
      "Carry out the five steps of risk assessment",
      "Understand your own duties under the law",
      "Know how and when to report incidents",
    ],
    slides: [
      { heading: "Key Legislation", visual: "grid",
        visualData: { items: ["HASAWA 1974", "Management Regs 1999", "RIDDOR 2013", "COSHH 2002", "Manual Handling 1992", "PUWER 1998"] },
        body: "Several laws underpin health and safety in care. The Health and Safety at Work Act 1974 is the foundation.",
        points: ["HASAWA places duties on employers and employees", "Regulations add specific requirements", "Your employer must provide training and a safe workplace"] },
      { heading: "Shared Responsibility", visual: "compare",
        visualData: { left: { title: "Employer must", items: ["Provide a safe workplace", "Assess and control risks", "Provide training and PPE", "Report serious incidents"] }, right: { title: "You must", items: ["Take care of yourself and others", "Co-operate with your employer", "Use equipment correctly", "Report hazards and near-misses"] } },
        body: "Health and safety is a shared duty between the employer and every member of staff.",
        points: ["You must not misuse anything provided for safety", "Reporting a near-miss can prevent a future injury"] },
      { heading: "Risk Assessment: 5 Steps", visual: "flow",
        visualData: { steps: ["Identify the hazards", "Decide who might be harmed", "Evaluate and control the risks", "Record and implement findings", "Review regularly"] },
        body: "A risk assessment is a careful look at what could cause harm, so you can weigh up sensible precautions.",
        points: ["A hazard is anything that could cause harm", "A risk is the chance of harm occurring", "Controls should reduce risk 'so far as reasonably practicable'"] },
      { heading: "RIDDOR — Reporting", visual: "grid",
        visualData: { items: ["Deaths", "Specified injuries", "7-day absences", "Occupational diseases", "Dangerous occurrences", "Gas incidents"] },
        body: "RIDDOR requires certain serious workplace events to be reported to the HSE.",
        points: ["Specified injuries include fractures and amputations", "Over-7-day absences are reportable", "Your manager makes the formal report — you must tell them"] },
      { heading: "Hazardous Substances (COSHH)", visual: "flow",
        visualData: { steps: ["Identify the substance", "Read the safety data sheet", "Store and label correctly", "Use the right PPE", "Dispose of safely"] },
        body: "COSHH covers cleaning chemicals, clinical waste and other substances hazardous to health.",
        points: ["Never decant chemicals into unlabelled bottles", "Follow the product's safety data sheet", "Report spillages and adverse reactions"] },
    ],
    quiz: [
      { q: "What is the primary health and safety law in the UK?", options: ["Management Regs 1999", "Health and Safety at Work Act 1974", "RIDDOR 2013", "Manual Handling Regs 1992"], answer: 1, explanation: "HASAWA 1974 is the primary, overarching legislation." },
      { q: "What does RIDDOR require?", options: ["Risk documentation", "Reporting of injuries, diseases and dangerous occurrences", "Manual handling training", "Substance control"], answer: 1, explanation: "RIDDOR 2013 requires reporting of specified workplace incidents to the HSE." },
      { q: "What is the first step of a risk assessment?", options: ["Evaluate the risks", "Record the findings", "Identify the hazards", "Decide who is harmed"], answer: 2, explanation: "You cannot control a hazard you have not first identified." },
      { q: "Under HASAWA, what duty do you have as an employee?", options: ["None — it's the employer's job", "Take reasonable care of yourself and others", "Only to wear a uniform", "Only to attend training"], answer: 1, explanation: "Employees must take reasonable care for their own safety and that of others." },
      { q: "What does COSHH cover?", options: ["Manual handling", "Substances hazardous to health", "Fire safety", "Working at height"], answer: 1, explanation: "COSHH 2002 covers the control of substances hazardous to health." },
      { q: "What is a 'near-miss'?", options: ["A minor injury", "An event that could have caused harm but didn't", "A reportable death", "A type of PPE"], answer: 1, explanation: "A near-miss is an event that could have caused harm; reporting it helps prevent future incidents." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "mental-capacity", title: "Mental Capacity Act", icon: "🧠", color: "#6C3483", duration: "40 min",
    summary: "Support decision-making and protect the rights of people who may lack capacity.",
    objectives: [
      "Apply the five principles of the Mental Capacity Act 2005",
      "Carry out the two-stage test of capacity",
      "Make and record best-interests decisions correctly",
      "Understand DoLS and Lasting Power of Attorney",
    ],
    slides: [
      { heading: "The 5 Key Principles", visual: "pillars",
        visualData: { items: ["Presume capacity", "Support decisions", "Unwise ≠ incapable", "Best interests", "Least restrictive"] },
        body: "The Mental Capacity Act 2005 protects and empowers people aged 16+ who may lack capacity to make particular decisions.",
        points: ["Assume capacity unless proven otherwise", "Give all practicable support to decide", "A person may make decisions others see as unwise", "Decisions for those lacking capacity must be in their best interests", "Always choose the least restrictive option"] },
      { heading: "Capacity is Decision-Specific", visual: "compare",
        visualData: { left: { title: "Capacity is...", items: ["About one decision at a time", "Assessed at the time needed", "Able to fluctuate", "Always presumed first"] }, right: { title: "Capacity is NOT...", items: ["About a diagnosis or label", "Permanent or all-or-nothing", "Based on others' opinions", "Removed by one unwise choice"] } },
        body: "A person may have capacity for some decisions but not others, and capacity can change over time.",
        points: ["Re-assess for each significant decision", "Maximise capacity — right time, place and support"] },
      { heading: "The 2-Stage Capacity Test", visual: "flow",
        visualData: { steps: ["Stage 1: Is there an impairment of mind or brain?", "Stage 2: Does it stop this decision?", "Can they understand the information?", "Retain, weigh and communicate it?"] },
        body: "To lack capacity, a person must fail the functional test because of an impairment of, or disturbance in, the mind or brain.",
        points: ["Failing any one of the four functional elements = lacks capacity for that decision", "Understand, retain, weigh, communicate", "Record how you reached your conclusion"] },
      { heading: "Best-Interests Decisions", visual: "grid",
        visualData: { items: ["Past wishes", "Present feelings", "Beliefs & values", "Consult family/carers", "Least restrictive", "Involve the person"] },
        body: "When someone lacks capacity for a decision, anything done for them must be in their best interests.",
        points: ["Consider their past and present wishes", "Consult those close to them", "Never make assumptions based on age or condition", "Encourage their own participation"] },
      { heading: "DoLS & LPA", visual: "compare",
        visualData: { left: { title: "DoLS", items: ["Authorises a deprivation of liberty", "Used in care homes & hospitals", "Must be the least restrictive option", "Has a right of review"] }, right: { title: "Lasting Power of Attorney", items: ["Appoints a decision-maker", "Property & Financial Affairs", "Health & Welfare", "Health LPA used only when capacity is lost"] } },
        body: "DoLS protects people who need restrictions for their safety; an LPA lets a trusted person decide on their behalf.",
        points: ["A deprivation of liberty must always be lawful", "Check whether an LPA is registered before deciding for someone"] },
    ],
    quiz: [
      { q: "What is the starting assumption about an adult's capacity?", options: ["A diagnosis means no capacity", "Capacity is presumed unless proven otherwise", "Capacity must be proven first", "The family decides"], answer: 1, explanation: "Principle 1: assume capacity unless it is established otherwise." },
      { q: "A person makes a decision others think is unwise. What does this tell you about their capacity?", options: ["They lack capacity", "An assessment is automatically needed", "Nothing — people may make unwise decisions", "You should call a GP"], answer: 2, explanation: "Making an unwise decision is not, by itself, evidence of incapacity." },
      { q: "How many functional elements must a person fail to lack capacity for a decision?", options: ["All four", "Three", "Two", "Any one"], answer: 3, explanation: "Failing any one of understand, retain, weigh, or communicate means lacking capacity for that decision." },
      { q: "A decision made for someone who lacks capacity must be...", options: ["The cheapest option", "What the family prefers", "In their best interests", "Decided by the manager"], answer: 2, explanation: "Anything done for a person lacking capacity must be in their best interests." },
      { q: "What does DoLS stand for?", options: ["Duty of Local Services", "Deprivation of Liberty Safeguards", "Decisions on Living Standards", "Default of Legal Support"], answer: 1, explanation: "DoLS — Deprivation of Liberty Safeguards — make a necessary deprivation of liberty lawful." },
      { q: "Capacity under the MCA is best described as...", options: ["Permanent once lost", "Based on a person's diagnosis", "Decision- and time-specific", "Decided by next of kin"], answer: 2, explanation: "Capacity is specific to each decision and the time it needs to be made." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "duty-of-care", title: "Duty of Care", icon: "🤝", color: "#1A5276", duration: "25 min",
    summary: "Understand your duty of care and how to balance safety with people's rights.",
    objectives: [
      "Explain what duty of care means in practice",
      "Balance duty of care with a person's right to choose",
      "Handle conflicts, dilemmas and complaints appropriately",
      "Raise concerns and whistleblow when necessary",
    ],
    slides: [
      { heading: "What is Duty of Care?", visual: "stat",
        visualData: { stats: [{ n: "Auto", l: "Arises from the care role" }, { n: "All", l: "Covers users, colleagues, visitors" }, { n: "0", l: "Times it can be delegated away" }] },
        body: "Duty of care is a legal obligation to act in the best interests of those you care for and to avoid acts or omissions that could foreseeably cause harm.",
        points: ["It arises automatically from the care relationship", "It applies to everyone affected by your work", "It cannot be passed off to someone else", "Breaching it can lead to disciplinary or legal action"] },
      { heading: "Duty vs Autonomy", visual: "compare",
        visualData: { left: { title: "Duty of care", items: ["Keep people safe from harm", "Act in their best interests", "Provide safe, good-quality care"] }, right: { title: "Right to choose", items: ["People with capacity may take risks", "They may refuse care or treatment", "Their choices must be respected"] } },
        body: "A frequent dilemma is balancing your duty to protect with a person's right to make their own choices.",
        points: ["A person with capacity may make 'risky' choices", "Support positive risk-taking, don't override it", "Where capacity is lacking, act in best interests", "Always assess, record and involve your manager"] },
      { heading: "Handling Complaints", visual: "flow",
        visualData: { steps: ["Listen and stay calm", "Apologise for the distress", "Record the complaint", "Pass it to your manager", "Follow the complaints procedure"] },
        body: "Complaints are a valuable source of improvement. Everyone has the right to complain and to be taken seriously.",
        points: ["Never be defensive or dismissive", "Reassure the person it will be looked into", "Know your organisation's complaints policy"] },
      { heading: "Raising Concerns & Whistleblowing", visual: "flow",
        visualData: { steps: ["Raise it with your line manager", "Escalate within your organisation", "Contact CQC if unresolved", "You are protected in law"] },
        body: "If you see poor or unsafe practice, you have a duty to speak up. Whistleblowers are protected under the law.",
        points: ["Duty of care outranks an unsafe instruction", "The Public Interest Disclosure Act protects you", "Acting in good faith is the key test", "Silence can allow harm to continue"] },
    ],
    quiz: [
      { q: "When does duty of care arise?", options: ["On signing a contract", "When a manager confirms it", "Automatically from the care relationship", "After a risk assessment"], answer: 2, explanation: "Duty of care arises automatically from the caring relationship." },
      { q: "A service user with capacity refuses their medication. What should you do?", options: ["Give it anyway", "Respect their choice, record it and inform your supervisor", "Call 999", "Get next-of-kin consent"], answer: 1, explanation: "A person with capacity may refuse treatment; forcing it would be unlawful." },
      { q: "A manager instructs you to do something you believe is unsafe. What do you do?", options: ["Follow it without question", "Leave your shift", "Raise your concern and escalate if it isn't resolved", "Comply quietly"], answer: 2, explanation: "Your duty of care takes precedence over an unsafe instruction; raise and escalate concerns." },
      { q: "How should you respond to a complaint?", options: ["Defend yourself firmly", "Listen, apologise for the distress and report it", "Ignore it if you disagree", "Tell them to put it in writing only"], answer: 1, explanation: "Listen, acknowledge the distress, record it and follow the complaints procedure." },
      { q: "What protects a worker who reports wrongdoing in good faith?", options: ["The Care Act 2014", "The Public Interest Disclosure Act", "RIDDOR", "COSHH"], answer: 1, explanation: "The Public Interest Disclosure Act 1998 protects whistleblowers acting in good faith." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "equality-diversity", title: "Equality, Diversity & Dignity", icon: "🌈", color: "#117A65", duration: "35 min",
    summary: "Promote equality, value diversity and protect the dignity of every person.",
    objectives: [
      "Identify the nine protected characteristics under the Equality Act 2010",
      "Recognise the four main types of discrimination",
      "Deliver person-centred, dignified care",
      "Apply the 6Cs to your everyday practice",
    ],
    slides: [
      { heading: "The Equality Act 2010", visual: "grid",
        visualData: { items: ["Age", "Disability", "Gender reassignment", "Marriage / civil partnership", "Pregnancy / maternity", "Race", "Religion / belief", "Sex", "Sexual orientation"] },
        body: "The Equality Act 2010 protects people from discrimination across nine 'protected characteristics'.",
        points: ["Discrimination on any of these grounds is unlawful", "Protection applies in work and in care", "Everyone is covered by the Act"] },
      { heading: "Equality, Diversity & Inclusion", visual: "pillars",
        visualData: { items: ["Equality", "Diversity", "Inclusion"] },
        body: "These three ideas work together to make sure everyone is treated fairly and feels they belong.",
        points: ["Equality — fair treatment and equal opportunity", "Diversity — valuing what makes people different", "Inclusion — everyone feels welcomed and respected", "Fair treatment is not the same as identical treatment"] },
      { heading: "Types of Discrimination", visual: "grid",
        visualData: { items: ["Direct", "Indirect", "Harassment", "Victimisation"] },
        body: "Discrimination can be obvious or hidden. The Equality Act recognises four main forms.",
        points: ["Direct — treating someone worse because of a characteristic", "Indirect — a rule that disadvantages a group", "Harassment — unwanted conduct that violates dignity", "Victimisation — treating someone badly for raising a concern"] },
      { heading: "Dignity in Care", visual: "compare",
        visualData: { left: { title: "Upholding dignity", items: ["Offer real choice", "Respect privacy", "Listen and involve", "Use preferred names"] }, right: { title: "Undermining dignity", items: ["Rushing personal care", "Talking over someone", "Ignoring preferences", "Exposing the body unnecessarily"] } },
        body: "Dignity means treating people as individuals and respecting what matters to them.",
        points: ["Person-centred care puts the individual first", "Small things make a big difference", "Privacy and respect are non-negotiable"] },
      { heading: "The 6Cs of Care", visual: "pillars",
        visualData: { items: ["Care", "Compassion", "Competence", "Communication", "Courage", "Commitment"] },
        body: "The 6Cs are the shared values that underpin compassionate, high-quality care.",
        points: ["Courage means speaking up when something is wrong", "Communication keeps care safe and personal", "Competence comes from training and reflection"] },
    ],
    quiz: [
      { q: "How many protected characteristics are in the Equality Act 2010?", options: ["6", "7", "9", "11"], answer: 2, explanation: "There are 9 protected characteristics." },
      { q: "Which of the 6Cs means speaking up when something is wrong?", options: ["Commitment", "Competence", "Courage", "Care"], answer: 2, explanation: "Courage means doing the right thing and speaking up." },
      { q: "A rule that unintentionally disadvantages one group is which type of discrimination?", options: ["Direct", "Indirect", "Harassment", "Victimisation"], answer: 1, explanation: "Indirect discrimination is a rule or practice that puts a group at a disadvantage." },
      { q: "What does person-centred care mean?", options: ["Treating everyone identically", "Putting the individual and their preferences first", "Following a fixed routine", "Letting family decide everything"], answer: 1, explanation: "Person-centred care focuses on the individual's needs, wishes and preferences." },
      { q: "Treating someone badly because they made a discrimination complaint is...", options: ["Direct discrimination", "Harassment", "Victimisation", "Indirect discrimination"], answer: 2, explanation: "Victimisation is treating someone unfairly for raising or supporting a complaint." },
      { q: "Which of these best upholds a person's dignity?", options: ["Choosing their clothes for them", "Using their preferred name and offering choice", "Rushing to save time", "Discussing them in front of others"], answer: 1, explanation: "Respecting preferences and offering real choice upholds dignity." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "medication", title: "Medication Awareness", icon: "💊", color: "#7B241C", duration: "45 min",
    summary: "Support people with medicines safely, accurately and within your role.",
    objectives: [
      "Apply the rights of safe medication support",
      "Complete MAR charts correctly and legally",
      "Distinguish prompting, assisting and administering",
      "Respond correctly to medication errors and refusals",
    ],
    slides: [
      { heading: "Levels of Support", visual: "pillars",
        visualData: { items: ["Prompting", "Assisting", "Administering"] },
        body: "Your role determines how you may support a person with their medicines. Never work beyond your training.",
        points: ["Prompting — reminding a person to take their medicine", "Assisting — practical help, e.g. opening a bottle", "Administering — giving the medicine directly", "Only administer if trained and assessed as competent"] },
      { heading: "The Rights of Medication", visual: "grid",
        visualData: { items: ["Right person", "Right medicine", "Right dose", "Right route", "Right time", "Right to refuse", "Right documentation"] },
        body: "Check every 'right', every time, before supporting any medicine.",
        points: ["Use at least two identifiers for the person", "Check the medicine, dose, route and time against the MAR", "A person always has the right to refuse", "Record immediately afterwards"] },
      { heading: "MAR Charts", visual: "compare",
        visualData: { left: { title: "Always", items: ["Sign immediately after giving", "Record refusals with a reason", "Use the correct code", "Keep the chart legible"] }, right: { title: "Never", items: ["Sign in advance", "Leave blank gaps", "Alter a previous entry", "Guess a missed entry"] } },
        body: "The Medication Administration Record is a legal document and must be accurate and complete.",
        points: ["A gap on a MAR chart is a serious error", "Use the agreed codes for refusals and omissions", "Charts are retained for a minimum of 8 years"] },
      { heading: "Medication Errors", visual: "flow",
        visualData: { steps: ["Stay calm — check the person", "Seek medical advice if needed", "Tell your manager immediately", "Record exactly what happened", "Complete an incident report"] },
        body: "If an error happens, the person's safety comes first, followed by honest and prompt reporting.",
        points: ["Never hide or 'correct' an error quietly", "Errors are reported so practice can improve", "Be open and honest — the duty of candour applies"] },
      { heading: "Special Situations", visual: "grid",
        visualData: { items: ["Controlled drugs", "Covert medication", "PRN (as required)", "Time-critical meds", "Self-administration", "Allergies"] },
        body: "Some medicines and circumstances need extra care and specific procedures.",
        points: ["Controlled drugs need a witness and separate records", "Covert medication needs a best-interests decision and pharmacist advice", "PRN needs a clear protocol", "Always check for documented allergies"] },
    ],
    quiz: [
      { q: "How many identifiers should you use to confirm a person before giving medication?", options: ["One", "At least two", "Three", "None if you know them"], answer: 1, explanation: "Use at least two identifiers (e.g. name and date of birth) every time." },
      { q: "When should you sign the MAR chart?", options: ["At the end of your shift", "Immediately after giving the medicine", "Before giving it", "Once the person confirms"], answer: 1, explanation: "Sign immediately after administering — never in advance." },
      { q: "How long must MAR charts be retained?", options: ["3 years", "5 years", "A minimum of 8 years", "12 years"], answer: 2, explanation: "MAR charts are kept for a minimum of 8 years." },
      { q: "What is the difference between prompting and administering?", options: ["No difference", "Prompting reminds; administering gives the medicine directly", "Administering is only for nurses", "Prompting needs no training at all"], answer: 1, explanation: "Prompting is reminding; administering is giving the medicine directly and needs competence." },
      { q: "A person refuses their medication. What should you do?", options: ["Insist they take it", "Hide it in their food", "Respect the refusal, record it and inform your manager", "Sign it as given"], answer: 2, explanation: "Respect the right to refuse, record it accurately, and report to your manager." },
      { q: "You realise you gave the wrong dose. What is your first priority?", options: ["Update the MAR quietly", "Check the person's wellbeing and seek advice", "Finish your round first", "Wait and see"], answer: 1, explanation: "The person's safety comes first — check them, seek advice, then report and record openly." },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "manual-handling", title: "Moving & Handling", icon: "🏋️", color: "#7D6608", duration: "35 min",
    summary: "Move and support people safely, protecting them and yourself from injury.",
    objectives: [
      "Understand the legislation governing moving and handling",
      "Assess a move using the TILE / LITE factors",
      "Apply safe handling principles and technique",
      "Use moving-and-handling equipment appropriately",
    ],
    slides: [
      { heading: "Why It Matters", visual: "stat",
        visualData: { stats: [{ n: "#1", l: "Cause of injury in social care" }, { n: "MSDs", l: "Musculoskeletal disorders" }, { n: "0", l: "Manual lifts where a hoist exists" }] },
        body: "Musculoskeletal injuries are the most common cause of harm to care workers. Safe handling protects everyone.",
        points: ["Never lift a person manually if an aid is available", "Poor technique causes long-term back injury", "Equipment exists to keep both of you safe"] },
      { heading: "The Legislation", visual: "grid",
        visualData: { items: ["HASAWA 1974", "Manual Handling Ops 1992", "LOLER 1998", "PUWER 1998", "Management Regs 1999"] },
        body: "The Manual Handling Operations Regulations 1992 require employers to avoid hazardous manual handling where possible.",
        points: ["Avoid — assess — reduce is the legal hierarchy", "LOLER covers lifting equipment like hoists", "Hoists must be serviced and inspected regularly"] },
      { heading: "Assess First — TILE", visual: "flow",
        visualData: { steps: ["Task — what is being done?", "Individual — your own capability", "Load — the person or object", "Environment — space and hazards"] },
        body: "Before any move, assess the TILE (or LITE) factors. Every person has a personal moving-and-handling plan.",
        points: ["Read the person's handling plan first", "Check the route and clear obstructions", "Never improvise an unplanned lift", "If anything has changed, reassess"] },
      { heading: "Safe Technique", visual: "compare",
        visualData: { left: { title: "Do", items: ["Bend your knees, not your back", "Keep the load close", "Maintain a stable base", "Move your feet to turn"] }, right: { title: "Don't", items: ["Twist or stoop", "Hold the load away from you", "Lift above shoulder height", "Rush or jerk the movement"] } },
        body: "Good technique keeps your spine protected and the move controlled and comfortable.",
        points: ["Keep a natural curve in your back", "Lead with your head, not your back", "Communicate with the person and any colleague"] },
      { heading: "Using Equipment", visual: "grid",
        visualData: { items: ["Hoists", "Slide sheets", "Transfer boards", "Stand aids", "Handling belts", "Wheelchairs"] },
        body: "The right equipment, used correctly, removes most of the risk from a move.",
        points: ["Only use equipment you are trained on", "Check equipment is serviced and undamaged before use", "Match the sling size and type to the person", "Two carers are needed for many hoist moves"] },
    ],
    quiz: [
      { q: "What does TILE stand for?", options: ["Task, Individual, Load, Environment", "Tilt, Incline, Lift, Extend", "Time, Injury, Lower, Engage", "Turn, Inspect, Lift, Evaluate"], answer: 0, explanation: "TILE: Task, Individual, Load, Environment — the factors to assess before a move." },
      { q: "When should you lift a person manually?", options: ["Always", "Only if no hoist or aid is available and it is assessed as safe", "Never under any circumstances", "Whenever it's quicker"], answer: 1, explanation: "Avoid manual lifting; use aids and follow the person's handling plan." },
      { q: "What is the most common cause of injury in social care?", options: ["Cuts", "Burns", "Musculoskeletal injuries", "Falls"], answer: 2, explanation: "Musculoskeletal injuries from poor moving and handling are the most common." },
      { q: "Which is correct safe technique?", options: ["Bend from the back and reach", "Bend your knees and keep the load close", "Twist as you lift", "Lift above your shoulders"], answer: 1, explanation: "Bend your knees, keep your back's natural curve, and hold the load close." },
      { q: "What does LOLER chiefly govern?", options: ["Cleaning chemicals", "Lifting equipment such as hoists", "Fire exits", "Food hygiene"], answer: 1, explanation: "LOLER 1998 covers lifting equipment, including the inspection of hoists." },
      { q: "Before using a hoist, you should...", options: ["Use any sling that's nearby", "Check it's serviced, undamaged and use the correct sling", "Work alone to save time", "Skip the handling plan"], answer: 1, explanation: "Check the equipment is safe and serviced, use the right sling, and follow the plan." },
    ],
  },
];

export const COURSE_IDS = COURSES.map(c => c.id);
export const COURSE_MAP = Object.fromEntries(COURSES.map(c => [c.id, c]));
